Added additional documentation for windows
pgh-public-meetings/city-scrapers-pitt pull request #186
Opened 2020-10-16 23:13 UTC by cheog

The documentation was about installing python on windows. Not sure if I'm doing this right.

2020-10-16 23:31 UTC, ben-nathanson requested changes
Spelling nitpicks aside, this looks great! If someone with a Windows machine could review this that would be great, but I trust you. 

Thanks!

Ben

2020-10-16 23:31 UTC, ben-nathanson commented on docs/installing_python.md
> +website. It is recommended to install the Microsoft Store as it is better
`It is recommended to install the Microsoft Store` -> 'It is recommended to install Python from the Microsoft Store'

2020-10-16 23:31 UTC, ben-nathanson commented on docs/installing_python.md
> +Open up the microsoft store and use the search to find python. Below is a
Capitalize `Microsoft Store`

2020-10-16 23:31 UTC, ben-nathanson commented on docs/installing_python.md
> +case that ypu have to use `python.exe` instead of `python`. Either way, you
`ypu` -> `you`

2020-10-16 23:31 UTC, ben-nathanson commented on docs/installing_python.md
> +a "Scripts" folder, however, by default windows doesn't know where that
Capitalize Windows

2020-10-16 23:31 UTC, ben-nathanson commented on docs/installing_python.md
> +list of folders. When you try to run a program like Pipenv windows will look
Capitalize Windows

2020-10-16 23:31 UTC, ben-nathanson commented on docs/setuphelp.md
> +If you want to install python on windows [click here](installing_python.md). If
Capitalize Windows

2020-10-16 23:31 UTC, ben-nathanson commented on docs/installing_python.md
> +# Installing Python On Pipenv Windows
`Installing Python On Pipenv Windows` -> `Installing Python on Windows With Pipenv`

2020-11-28 01:22 UTC, bonfirefan commented
I'm going to merge this, and we can correct spelling in a future update.

2020-11-28 01:23 UTC, merged