Added spider for Allegheny County Jail Oversight Board
pgh-public-meetings/city-scrapers-pitt pull request #187
Opened 2020-10-16 23:23 UTC by woodyeagle

New Spider

2020-10-28 13:24 UTC, ben-nathanson requested changes

2020-10-28 13:24 UTC, ben-nathanson commented on city_scrapers/spiders/jail_oversight.py
> +            #        for item in response.css("div.entry-content p").re('.*'):
Be sure to remove this ghost code before making a final push.

2020-10-28 13:24 UTC, ben-nathanson commented on city_scrapers/spiders/jail_oversight.py
> +        #        datetext = re.search(r"[ADFJMNOS][a-z]{2,8}\s[1-3]?[0-9],\s[12][0-9]{3}", item)
Be sure to remove this ghost code here as well.

2020-10-28 13:24 UTC, ben-nathanson commented on city_scrapers/spiders/jail_oversight.py
> +        if meeting_date > datetime(2020, 5, 1):
I like how you dealt with this problem! Ideally, there would be a way to determine the location more dynamically (e.g. regex the event for the words "online") but the structure of the Jail Oversight Board page makes that unlikely.

2020-10-28 13:24 UTC, ben-nathanson commented on city_scrapers/spiders/jail_oversight.py
> +        if meeting_date > datetime(2020, 5, 1):
Assuming the Board returns to in-person meetings at some point, we will need to refactor this in the future. But this is a tiny amount of tech debt.

2020-10-28 13:24 UTC, ben-nathanson commented on tests/test_jail_oversight.py
> +# def test_tests():
Good to see you taking advantage of tests! Two general points:

1. Be sure to remove commented-out code throughout this file. 
1. Make sure that you're committing the `jail_oversight.html` file. This is why our tests failed on the most recent commit in this PR. `jail_oversight.html` should have been created when you ran `scrapy genspider ...`. We'll also be available this Friday to go into more depth on this if that's helpful. Join our Meetup [here](https://www.meetup.com/codeforpgh/events/tfsjzrybcnbnc/).

2020-11-14 00:31 UTC, mishugana approved these changes

2020-11-14 00:32 UTC, merged