Add pa_mt_lebanon spider
pgh-public-meetings/city-scrapers-pitt pull request #200
Opened 2020-11-07 23:44 UTC by maxachis

2020-11-14 00:16 UTC, ben-nathanson commented
For consistency, this spider should be renamed to `mt_lebo_public_meetings`. `pa_mt_lebo_public_meetings` lumps it in with other state-wide agencies and could potentially be confusing.

2020-11-14 00:37 UTC, ben-nathanson requested changes
When I ran `scrapy crawl pa_mt_lebanon` I found an `IndexError` click [here](https://pastebin.com/hhzsNyvH) for logs.

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +        """Parse start datetime as a naive datetime object."""
For consistency move those comment up to line 64 / the first line after the method definition.

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +        """Parse or generate links."""
Same comment here - move this comment up

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +        pattern = "[Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec]\S* \d+"
Make this into a constant

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +            pattern = "\*\*"
Make this into a constant

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +            if re.search(pattern, eventString) != None:
For readability, make this into an if-else.

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +        pattern = "[Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec]\S*"
Make this into a constant

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +        pattern = "[Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec]\S* (\d+)"
Make this into a constant

2020-11-14 00:37 UTC, ben-nathanson commented on city_scrapers/spiders/pa_mt_lebo_public_meetings.py
> +        pattern = "[Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec]\S*"
There's an opportunity for code reuse here

2020-11-14 01:01 UTC, ben-nathanson commented
There are 46 files associated with this - mostly related to tests - can we get rid of any them without affecting regression tests? If I takes more than 20 minutes don't worry about it but that's a lot of info.

2020-11-15 20:30 UTC, maxachis commented
> There are 46 files associated with this - mostly related to tests - can we get rid of any them without affecting regression tests? If I takes more than 20 minutes don't worry about it but that's a lot of info.

After looking into this, the answer is yes, with the caveat that unless we modify the HTML file itself, we can't remove the  "pa_mt_lebanon_files" directory. The HTML file references that _a lot_--46 times--and even if it doesn't get the files in the folder, so long as it can reference the folder itself, it functions fine. If the folder isn't there, though, it throws an error. 

If it seems stupid to keep an empty folder, the answer is yes, but it's either that or painstakingly removing the HTML references, which I'm willing to do if necessary (especially since it might confuse people working on this later on as to why we have an empty folder), but which seems so tightly wound in the thoroughly convoluted HTML code that resolving that might be more trouble than it's worth.

2020-11-15 22:03 UTC, ben-nathanson requested changes
This looks good! Just be sure to get the naming consistent with the other spiders:
- rename the class and variables
- rename the file/directory names

If it would be simpler, you could just do `scrapy genspider ...` and copy the code into the newly named files/directories/variables.

2020-11-20 01:18 UTC, maxachis commented on city_scrapers/spiders/mt_lebo_public_meetings.py
> +monthAndDayPattern = "[Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec]\S* \d+"
Thank you! I'm quickly growing quite attached to Regex.

2020-11-20 01:43 UTC, maxachis commented
> When I ran `scrapy crawl pa_mt_lebanon` I found an `IndexError` click [here](https://pastebin.com/hhzsNyvH) for logs.

This was related to what I was saying about the rickety nature of the website -- and hence, at least previously, the spider. I modified the spider to be a bit more flexible. In this case, it's looking more for keywords rather than specific id's, which are either sparse or a sequence of near-random-seeming characters.

2020-11-29 02:52 UTC, ben-nathanson approved these changes
Looks good! Tested locally. Thank you for incorporating my suggestions about naming conventions. IMO they can be a bit pedantic but it helps keep a clean house. 

🚢 it.

2021-01-09 01:22 UTC, bonfirefan commented
Max, great spider. I would note that you can check for month date patterns without having to specify them - you could use something clever with datetime's `%b` tag which recognize abbreviated months like Jan / Feb / Mar

2021-01-09 01:22 UTC, merged